### ISSUE TITLE
Windows don't render with rasterizer

### ISSUE THREAD

**Issue by TheZoq2** [lucasmerlin/egui_skia#11]
I was expecting `cargo run --example rasterizer --features cpu_fix` to render a few windows but it does not. It only renders the sidebar, the menu, and a transparent area in between 

![output](https://github.com/lucasmerlin/egui_skia/assets/5312813/9e15eed6-1433-413b-a16a-baf71dcd13ec)

**Comment by lucasmerlin** [comment]
The problem is that egui doesn't render windows on the first frame, I think because it doesn't know their sizes yet. 

I've released egui_skia 0.4.0 adding an option to rasterize to set how many frames should be rendered before the screenshot is taken, and made the default 2 so windows are always visible. Does this fix your problem as well?

**Comment by TheZoq2** [comment]
That did the trick, thanks for the quick fix!
